### ISSUE TITLE
validation error happens during training phase

### ISSUE THREAD

**Issue by white2007** [meijieru/crnn.pytorch#58]
Hi,

The following error happens while validating during train process. 
Would you please tell me how to fix it? Thanks. 

```
Start val
Traceback (most recent call last):
  File "crnn_main.py", line 215, in <module>
    val(crnn, test_dataset, criterion)
  File "crnn_main.py", line 162, in val
    sim_preds = converter.decode(preds.data, preds_size.data, raw=False)
  File "/home/wanghz/crnn.pytorch/utils.py", line 82, in decode
    assert t.numel() == length.sum(), "texts with length: {} does not match declared length: {}".format(t.numel(), length.sum())
AssertionError: texts with length: 1664 does not match declared length: 3328

**Comment by meijieru** [comment]
If this will happen if not use multi gpu?

**Comment by white2007** [comment]
I tried one gpu just now. The program works fine. however the training does not show good consequence for my own dateset.  

It looks like multi-gpu leads to such problems.

**Comment by white2007** [comment]
I create 6400 training images with 4 letters or digits, whose resolution is 274*74. Then I train 100 epochs with batch_size of 64. However, it shows no convergence. The following log tells in detail.

would u pls tell me what's wrong with it? thanks

2017-08-23 18:22:11,993 - root - DEBUG - [epoch:100/100 batch:10/100 batch_size:64] Loss: 21.5575119019
2017-08-23 18:22:12,519 - root - DEBUG - [epoch:100/100 batch:20/100 batch_size:64] Loss: 19.4152982712
2017-08-23 18:22:13,048 - root - DEBUG - [epoch:100/100 batch:30/100 batch_size:64] Loss: 21.3406339645
2017-08-23 18:22:13,595 - root - DEBUG - [epoch:100/100 batch:40/100 batch_size:64] Loss: 21.8175168991
2017-08-23 18:22:14,140 - root - DEBUG - [epoch:100/100 batch:50/100 batch_size:64] Loss: 24.2895008087
2017-08-23 18:22:14,677 - root - DEBUG - [epoch:100/100 batch:60/100 batch_size:64] Loss: 18.8902362823
2017-08-23 18:22:15,221 - root - DEBUG - [epoch:100/100 batch:70/100 batch_size:64] Loss: 22.1881462097
2017-08-23 18:22:15,761 - root - DEBUG - [epoch:100/100 batch:80/100 batch_size:64] Loss: 23.4686908722
2017-08-23 18:22:16,299 - root - DEBUG - [epoch:100/100 batch:90/100 batch_size:64] Loss: 24.4427461624
2017-08-23 18:22:16,839 - root - DEBUG - [epoch:100/100 batch:100/100 batch_size:64] Loss: 19.2434511185
2017-08-23 18:22:16,839 - root - DEBUG - Start val
2017-08-23 18:22:17,521 - root - DEBUG - -------------------------- =>                     , gt: vbys                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: p7ug                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: schy                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: vmts                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: x7dk                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: kiyz                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: y9cz                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: vdre                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: hoxs                
2017-08-23 18:22:17,522 - root - DEBUG - -------------------------- =>                     , gt: etkc                
2017-08-23 18:22:17,522 - root - DEBUG - Test loss: 20.130669, accuracy: 0.000000

**Comment by meijieru** [comment]
Since it has been solved, I close it.

**Comment by haikuoyao** [comment]
Hi  @white2007  Does it work on multi-gpu now ?

**Comment by tqx0808** [comment]
multi-gpu still appear such error

**Comment by haikuoyao** [comment]
@tqx0808 yeah it seems something wrong in the validation phase.  
https://github.com/meijieru/crnn.pytorch/blob/master/crnn_main.py#207 
If this line is commented, it works.

**Comment by SDASDASA** [comment]
@meijieru i still encountered the same problem with the latest version，can you point out where the problem is. thanks.
 assert t.numel() == length.sum(), "texts with length: {} does not match declared length: {}".format(t.numel(), length.sum())

**Comment by meijieru** [comment]
@SDASDASA Sorry, I am really busy now. I will fix this problem once I am free.

**Comment by SDASDASA** [comment]
@meijieru ok,thanks.

**Comment by rabbithui** [comment]
@meijieru i still have this problem, has it been solved now ? thanks.

**Comment by akshitac8** [comment]
Has anyone solved this issue now?

**Comment by zhenming33** [comment]
crnn model on multi gpu return each preds stacking on the first channel while the first channel is the time sequence. so, should resize the pred to correct size to solve this problem
